const container = document.createElement("main");
container.classList.add("container");
const content = document.createElement("div");
content.classList.add("content");
const contentImage = document.createElement("article");
contentImage.classList.add("content-img");
const nft = document.createElement("img");
nft.src = "images/image-equilibrium.jpg";
const contentEye = document.createElement("div");
contentEye.classList.add("svg");
const eye = document.createElement("img");
eye.src = "images/icon-view.svg";

const description = document.createElement("section");
description.classList.add("description");
const title = document.createElement("h3");
title.textContent = "Equilibrium #3429";
title.classList.add("title");
const text = document.createElement("p");
text.textContent = " Our Equilibrium collection promotes balance and calm.";
text.classList.add("text");
const prices = document.createElement("section");
prices.classList.add("prices");
const contentDinner = document.createElement("article");
contentDinner.classList.add("content-dinner");
const dinner = document.createElement("p");
dinner.textContent = "0.041 ETH";
const dinnerImg = document.createElement("img");
dinnerImg.src = "images/icon-ethereum.svg";

const contentDays = document.createElement("article");
contentDays.classList.add("content-dinner");
const days = document.createElement("p");
days.textContent = "3 days left";
const daysImg = document.createElement("img");
daysImg.src = "images/icon-clock.svg";
const hr = document.createElement("hr");
const contentProfile = document.createElement("article");
contentProfile.classList.add("content-photo");
const avatar = document.createElement("img");
avatar.src = "images/image-avatar.png";
avatar.classList.add("img-photo");
const writtenAvatar = document.createElement("p");
writtenAvatar.textContent = "Creation of ";
writtenAvatar.classList.add("name2");
const nameAvatar = document.createElement("span");
nameAvatar.textContent = "Jules Wyvern";
nameAvatar.classList.add("name");

document.body.appendChild(container);
container.appendChild(content);
content.appendChild(contentImage);
contentImage.appendChild(nft);
contentImage.appendChild(contentEye);
contentEye.appendChild(eye);
content.appendChild(description);
description.appendChild(title);
description.appendChild(text);
description.appendChild(prices);
prices.appendChild(contentDinner);
contentDinner.appendChild(dinnerImg);
contentDinner.appendChild(dinner);
prices.appendChild(contentDays);
contentDays.appendChild(daysImg);
contentDays.appendChild(days);
description.appendChild(hr);
description.appendChild(contentProfile);
contentProfile.appendChild(avatar);
contentProfile.appendChild(writtenAvatar);
writtenAvatar.appendChild(nameAvatar);
